version: "1"
services:
- type: web
  name: bun-react-vite
  runtime: static
  repo: https://github.com/robdimarco-render/example-bun-app
  branch: main
  envVars:
  - key: SKIP_NODE_INSTALL
    value: true
  - key: SKIP_RUBY_INSTALL
    value: true
  - key: SKIP_PYTHON_INSTALL
    value: true
  buildCommand: bun install; bun --bun vite build
  staticPublishPath: dist
  rootDir: bun-react-vite
- type: web
  name: bun-express
  runtime: node
  repo: https://github.com/robdimarco-render/example-bun-app
  branch: main
  plan: starter
  region: oregon
  buildCommand: bun install
  startCommand: bun server.ts
  rootDir: bun-express
- type: web
  name: bun-express
  runtime: bogus
